version: '3.8'

services:
  openstack-rca-system:
    image: chandanbam/openstack-rca-system:latest
    container_name: openstack-rca-system
    ports:
      - "7051:7051"
    volumes:
      # Vector database data
      - ./data/vector_db:/app/data/vector_db
      # Cache data
      - ./data/cache:/app/data/cache
      # LSTM models
      - ./models:/app/models
      # Log files
      - ./logs:/app/logs
      # Temporary files for S3 downloads
      - ./temp:/app/temp
    environment:
      # MLflow configuration (optional)
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-}
      - MLFLOW_ARTIFACT_ROOT=${MLFLOW_ARTIFACT_ROOT:-}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL:-}
      - MLFLOW_ENABLED=${MLFLOW_ENABLED:-false}
      
      # AWS credentials for S3 model storage (optional)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-}
      
      # Anthropic API key for RCA analysis
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      
      # Container configuration
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=7051
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7051/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0' 